/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as EstablishmentsLocalAuthorityIdImport } from './routes/establishments/$localAuthorityId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EstablishmentsLocalAuthorityIdRoute =
  EstablishmentsLocalAuthorityIdImport.update({
    id: '/establishments/$localAuthorityId',
    path: '/establishments/$localAuthorityId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/establishments/$localAuthorityId': {
      id: '/establishments/$localAuthorityId'
      path: '/establishments/$localAuthorityId'
      fullPath: '/establishments/$localAuthorityId'
      preLoaderRoute: typeof EstablishmentsLocalAuthorityIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/establishments/$localAuthorityId': typeof EstablishmentsLocalAuthorityIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/establishments/$localAuthorityId': typeof EstablishmentsLocalAuthorityIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/establishments/$localAuthorityId': typeof EstablishmentsLocalAuthorityIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/establishments/$localAuthorityId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/establishments/$localAuthorityId'
  id: '__root__' | '/' | '/establishments/$localAuthorityId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstablishmentsLocalAuthorityIdRoute: typeof EstablishmentsLocalAuthorityIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstablishmentsLocalAuthorityIdRoute: EstablishmentsLocalAuthorityIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/establishments/$localAuthorityId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/establishments/$localAuthorityId": {
      "filePath": "establishments/$localAuthorityId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
